### ISSUE TITLE
ReferenceError: restful is not defined at lib/restful.js:80:9

### ISSUE THREAD

**Issue by cronopio** [flatiron/restful#8]
Today doing some tests using restful as a flatiron plugin I notice this error. You can replicate the error running [the example app](https://github.com/flatiron/restful/blob/master/examples/app.js).

```
~/Nodejitsu/flatiron/restful/examples (master ✘)✭ ᐅ node app.js 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
ReferenceError: restful is not defined
    at /home/cronopio/Nodejitsu/flatiron/restful/lib/restful.js:80:9
    at Array.forEach (native)
    at [object Object].<anonymous> (/home/cronopio/Nodejitsu/flatiron/restful/lib/restful.js:71:32)
    at initPlugin (/home/cronopio/Nodejitsu/flatiron/restful/node_modules/flatiron/node_modules/broadway/lib/broadway/app.js:97:40)
    at /home/cronopio/Nodejitsu/flatiron/restful/node_modules/utile/node_modules/async/lib/async.js:86:13
    at Array.forEach (native)
    at /home/cronopio/Nodejitsu/flatiron/restful/node_modules/utile/node_modules/async/lib/async.js:26:24
    at Object.forEach (/home/cronopio/Nodejitsu/flatiron/restful/node_modules/utile/node_modules/async/lib/async.js:85:9)
    at initPlugins (/home/cronopio/Nodejitsu/flatiron/restful/node_modules/flatiron/node_modules/broadway/lib/broadway/app.js:112:11)
    at /home/cronopio/Nodejitsu/flatiron/restful/node_modules/flatiron/node_modules/broadway/lib/broadway/bootstrapper.js:63:5

```

So I want to take care of this, writing the needed test for flatiron integration.

**Comment by cronopio** [comment]
Its seems a simple `s/restful/exports/g` correction. I will write the test and the pull request
